server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 192.168.161.101:22122
ly:
  upload:
    baseUrl: http://image.leyou.com
    allowTypes:
      - image/jpeg
      - image/png
      - image/bmp
      - image/gif